let
    Source = {Number.From(Date.FromText("1-1-1995"))..Number.From(Date.FromText("31-12-2025"))},
    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Column1", type date}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Date"}}),
    #"Added Year" = Table.AddColumn(#"Renamed Columns", "Year", each Date.Year([Date]), Int64.Type),
    #"Added Month" = Table.AddColumn(#"Added Year", "Month", each Date.Month([Date]), Int64.Type),
    #"Added Month Name" = Table.AddColumn(#"Added Month", "Month Name", each Date.MonthName([Date]), type text),
    #"Added Month Name Short" = Table.AddColumn(#"Added Month Name", "Month Name Short", each Date.ToText([Date],"MMM"), type text),
    #"Added Quarter" = Table.AddColumn(#"Added Month Name Short", "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),
    #"Added Quarter Name" = Table.AddColumn(#"Added Quarter", "Quarter Name", each "Q"&Text.From([Quarter]), type text),
    #"Added Day" = Table.AddColumn(#"Added Quarter Name", "Day", each Date.Day([Date]), Int64.Type),
    #"Added Start of Month" = Table.AddColumn(#"Added Day", "Start of Month", each Date.StartOfMonth([Date]), type date),
    #"Added End of Month" = Table.AddColumn(#"Added Start of Month", "End of Month", each Date.EndOfMonth([Date]), type date),
    #"Added Is Leap Year" = Table.AddColumn(#"Added End of Month", "Is Leap Year", each Date.IsLeapYear([Date]), type logical),
    #"Added Day of Year" = Table.AddColumn(#"Added Is Leap Year", "Day of Year", each Date.DayOfYear([Date]), Int64.Type),
    #"Added Day of Week" = Table.AddColumn(#"Added Day of Year", "Day of Week", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
    #"Added Day of Week Name" = Table.AddColumn(#"Added Day of Week", "Day of Week Name", each Date.DayOfWeekName([Date]), type text),
    #"Added Day of Week Name short" = Table.AddColumn(#"Added Day of Week Name", "Day of Week Name short", each Date.ToText([Date],"ddd"), type text),
    #"Added Start of Year" = Table.AddColumn(#"Added Day of Week Name short", "Start of Year", each Date.StartOfYear([Date]), type date),
    #"Added End of Year" = Table.AddColumn(#"Added Start of Year", "End of Year", each Date.EndOfYear([Date]), type date),
    #"Added Current Date" = Table.AddColumn(#"Added End of Year", "Current Date", each Date.From(DateTime.LocalNow()), type date),
    #"Added Current Day" = Table.AddColumn(#"Added Current Date", "Current Day", each Date.IsInCurrentDay([Date]), type logical),
    #"Added Current Month" = Table.AddColumn(#"Added Current Day", "Current Month", each Date.IsInCurrentMonth([Date]), type logical),
    #"Added Current Year" = Table.AddColumn(#"Added Current Month", "Current Year", each Date.IsInCurrentYear([Date]), type logical),
    #"Added Week" = Table.AddColumn(#"Added Current Year", "Week", each Date.WeekOfYear([Date]), Int64.Type),
    #"Added Day Index" = Table.AddColumn(#"Added Week", "Day Index", each Duration.Days([Date]-Date.From(DateTime.LocalNow())), Int64.Type),
    #"Added Month Index" = Table.AddColumn(#"Added Day Index", "Month Index", each 12 * ( [Year] - Date.Year( DateTime.LocalNow() ) ) + [Month] - Date.Month(DateTime.LocalNow()), Int64.Type),
    #"Added Year Index" = Table.AddColumn(#"Added Month Index", "Year Index", each [Year] - Date.Year( DateTime.LocalNow()), Int64.Type),
    #"Added Year Month Sort" = Table.AddColumn(#"Added Year Index", "Year Month Sort", each [Year]*100+[Month], Int64.Type),
    #"Added Year MonthName" = Table.AddColumn(#"Added Year Month Sort", "Year Monthname", each Text.Combine({Number.ToText([Year]), "-", [Month Name Short]}), type text),
    #"Added Year Month" = Table.AddColumn(#"Added Year MonthName", "Year Month", each Text.Combine({Number.ToText([Year]), "-", Number.ToText([Month])}), type text),
    #"Added Year Week Sort" = Table.AddColumn(#"Added Year Month", "Year Week Sort", each [Year]*100+[Week], Int64.Type),
    #"Added Year Week" = Table.AddColumn(#"Added Year Week Sort", "Year-Week", each Text.Combine({Number.ToText([Year]), "-", Number.ToText([Week])}), type text),
    Target = #"Added Year Week"
in
   Target
